name: windows-debug

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc, mingw]
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.23'

      - name: Setup MinGW (if needed)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
        if: matrix.compiler == 'mingw'

      - name: Configure and Build (MSVC)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 2022"
          cmake --build . --config Debug
        if: matrix.compiler == 'msvc'

      - name: Configure and Build (MinGW)
        shell: msys2 {0}
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"
          cmake --build .
        if: matrix.compiler == 'mingw'

      - name: Run Unit Tests
        run: |
          cd build
          ctest --config Debug --output-on-failure
        if: success()

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-build
          path: |
            build/TrialAndError/
            !build/TrialAndError/**/*.pdb
        if: always()